apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: wanderlust-frontend
  namespace: argo

  annotations:

    argocd-image-updater.argoproj.io/image-list: frontend=akstestingtrialcrrt.azurecr.io/wanderlust-frontend

    argocd-image-updater.argoproj.io/frontend.update-strategy: semver

    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$

    argocd-image-updater.argoproj.io/write-back-method: git

    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/guptamadhur409-spec/wanderlust-gitops.git
    targetRevision: main
    path: apps/frontend/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: wanderlust

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true