apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

replicas:
- name: frontend-deployment
  count: 3

images:
- name: akstestingtrialcrrt.azurecr.io/wanderlust-frontend
  newTag: v1.0.3  
